# Generated by Django 2.1 on 2018-12-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('place_name', models.CharField(max_length=50)),
                ('admin_name', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitutde', models.FloatField()),
                ('accuracy', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
